version: 2
updates:
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "daily"
      labels:
          - "github-actions"
          - "dependencies"
      commit-message:
          prefix: "chore"
          include: "scope"

    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "daily"
      labels:
          - "npm"
          - "dependencies"
      ignore:
          - dependency-name: "typescript"
            versions: ["5.x"]
      commit-message:
          prefix: "chore"
          include: "scope"
      versioning-strategy: increase

    - package-ecosystem: "docker"
      directory: "/"
      schedule:
          interval: "weekly"
      labels:
          - "docker"
          - "dependencies"
      commit-message:
          prefix: "chore"
          include: "scope"
