name: 💡 Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement"]
assignees:
    - sunaookamishirokodev
body:
    - type: markdown
      attributes:
          value: |
              Thanks for taking the time to suggest a new feature!

    - type: dropdown
      id: feature-type
      attributes:
          label: Feature Type
          description: What type of feature is this?
          options:
              - Performance Improvement
              - Security Feature
              - User Feature
              - Third-party Integration
              - Documentation
              - Other
      validations:
          required: true

    - type: textarea
      id: problem
      attributes:
          label: Current Problem
          description: What problem does this feature solve?
          placeholder: I'm always frustrated when...
      validations:
          required: true

    - type: textarea
      id: solution
      attributes:
          label: Proposed Solution
          description: Describe your solution in detail
      validations:
          required: true

    - type: textarea
      id: alternatives
      attributes:
          label: Alternative Solutions
          description: What alternative solutions have you considered?

    - type: textarea
      id: additional
      attributes:
          label: Additional Context
          description: Add any other context or screenshots about the feature request

    - type: checkboxes
      id: terms
      attributes:
          label: Code of Conduct
          description: By submitting this feature request, you agree to follow our Code of Conduct
          options:
              - label: I agree to follow this project's Code of Conduct
                required: true
